### ISSUE TITLE
Not working on post back event

### ISSUE THREAD

**Issue by Jmocke** [issamalidev/bs.pagination.js#1]
i am using Linq to populate my gridview , but on Page Index Changing event , the style disappears

**Comment by issamalidev** [comment]
Do you use it inside UpdatePanel? if yes; please check my blog, there are some workarounds in the comments here: http://blog.issamsoft.com/index.php?q=en/node/73

**Comment by Jmocke** [comment]
ok thank you i fixed looking at your post in stackoverflow

http://stackoverflow.com/questions/22420602/simple-script-to-apply-bootstrap-pagination-style-in-asp-net-gridview
